apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-redis-app
  template:
    metadata:
      labels:
        app: node-redis-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}"
